name: Build, publish and deploy frontend

on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build app and build docker image
        run: docker build . -t supix/vmmate:latest -f .Dockerfile.prod
      - name: Publish docker image to Docker hub
        run: |
          docker login -u supix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push supix/vmmate:latest
